// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csipbbnhzcimujaghzbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzaXBiYm5oemNpbXVqYWdoemJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Nzk4NDgsImV4cCI6MjA2MjA1NTg0OH0.czuL1gZiavq2_hHDkD2biaXUcNHq689tEp9PszHPqM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);